### ISSUE TITLE
Add custom model data filter

### ISSUE THREAD

**Issue by sehrschlechtYT** [sehrschlechtYT/KeepItems#12]
Filters items by item type and custom model data

Example:
```yml
custom-model-data:
  enabled: true
  items:
    - DIAMOND_SWORD:12345
```
would filter all items that are diamond swords and have a custom model data of 12345.
